# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3OGQbs3UOTzPfO71rlbpw290bgOqTSV
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df=pd.read_csv('breast-cancer.csv')
df

X=df.drop('diagnosis', axis=1)
y=df['diagnosis']

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

X_train,X_test,y_train,y_test=train_test_split(X_scaled, y,test_size=0.2,random_state=42)

linear_svm=SVC(kernel='linear')
linear_svm.fit(X_train, y_train)

y_pred_linear=linear_svm.predict(X_test)
print("Linear SVM Accuracy:", accuracy_score(y_test, y_pred_linear))
print(classification_report(y_test, y_pred_linear))

rbf_svm=SVC(kernel='rbf',gamma='scale')
rbf_svm.fit(X_train,y_train)

y_pred_rbf=rbf_svm.predict(X_test)
print("RBF SVM Accuracy:", accuracy_score(y_test,y_pred_rbf))
print(classification_report(y_test,y_pred_rbf))

y_numeric=y.map({'M': 1, 'B': 0})

param_grid={
    'C':[0.1, 1, 10, 100],
    'gamma':[1, 0.1, 0.01, 0.001],
    'kernel':['rbf']
}

grid=GridSearchCV(SVC(), param_grid, refit=True, verbose=1)
grid.fit(X_train, y_train)

print("Best Parameters:",grid.best_params_)
print("Best Score:",grid.best_score_)

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca=PCA(n_components=2)
X2D=pca.fit_transform(X_scaled)

y_colors=y_numeric.values

plt.figure(figsize=(8, 6))
plt.scatter(X2D[:, 0], X2D[:, 1], c=y_colors, cmap='coolwarm')
plt.title("Breast Cancer Data (PCA 2D) with SVM Classes")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.colorbar(label="Class (0 = B, 1 = M)")
plt.show()



